name: push-webui

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to be used when pushing components to the Docker Hub."
        required: true
        type: string
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string

defaults:
  run:
    shell: bash -xe {0}

jobs:
  push-webui:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit
          submodules: recursive

      - uses: nixbuild/nix-quick-install-action@v34
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g
      - name: Populate the nix store
        run: |
          nix develop .#withObelisk --command echo

      - name: Log in to Docker Hub
        run: |
          echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Populate the nix store
        run: nix develop  .#withObelisk --command echo

      - name: Generate Unique Branch Name
        id: branch-name
        run: echo "branch_name=bump-webui-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Clone Obelisk repo
        run: |
          git clone https://${{ secrets.GH_TOKEN_OBELISK_RW }}@github.com/obeli-sk/obelisk.git

      - name: Push webui
        run: |
          nix develop  .#withObelisk --command ./scripts/push-webui.sh $TAG obelisk/assets/webui-version.txt
        env:
          TAG: ${{ github.event.inputs.tag }}

      - name: Configure git before push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: obelisk

      - name: Create a PR
        run: |
          git checkout -b ${{ steps.branch-name.outputs.branch_name }}
          git add assets/webui-version.txt
          git commit -m "chore: Bump webui to $TAG"
          git push origin ${{ steps.branch-name.outputs.branch_name }}
          curl -v --fail -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/obeli-sk/obelisk/pulls \
            -d '{
              "title": "chore: Bump webui",
              "head": "'${{ steps.branch-name.outputs.branch_name }}'",
              "base": "main",
              "body": ""
            }'
        env:
          TAG: ${{ github.event.inputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PR_RW }}
        working-directory: obelisk
